global:
  scrape_interval: 10s

scrape_configs:
  - job_name: service-level-operator
    scrape_interval: 10s
    static_configs:
      - targets: ["operator:8080"]
        labels:
          mode: fake
          environment: dev
